import "./globals.css";
import { Inter } from "next/font/google";
import AuthProvider from "@/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <div className="w-[90%] mx-auto h-full">{children}</div>
        </body>
      </AuthProvider>
    </html>
  );
}
